//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camere()
        {
            this.Rezervari = new HashSet<Rezervari>();
        }
    
        public int CameraID { get; set; }
        public int CazareID { get; set; }
        public string Adresa { get; set; }
        public int NumarPaturi { get; set; }
        public int PretPerNoapte { get; set; }
        public byte[] Poza { get; set; }
    
        public virtual Cazare Cazare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervari> Rezervari { get; set; }
    }
}
