//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obiective
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obiective()
        {
            this.PozeActivitati = new HashSet<PozeActivitati>();
            this.RecenziiActivitati = new HashSet<RecenziiActivitati>();
        }
    
        public int ObiectivID { get; set; }
        public string Denumire { get; set; }
        public string Locatie { get; set; }
        public int OrasID { get; set; }
        public int CategorieID { get; set; }
        public byte[] Poza { get; set; }
    
        public virtual CategoriiObiective CategoriiObiective { get; set; }
        public virtual Orase Orase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozeActivitati> PozeActivitati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecenziiActivitati> RecenziiActivitati { get; set; }
    }
}
