//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisor
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecenziiActivitati
    {
        public int RecenzieID { get; set; }
        public int UserID { get; set; }
        public int ObiectivID { get; set; }
        public int Stele { get; set; }
        public string Comentarii { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Obiective Obiective { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
