//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurante()
        {
            this.RecenziiRestaurante = new HashSet<RecenziiRestaurante>();
            this.PozeRestaurante = new HashSet<PozeRestaurante>();
            this.Preparate = new HashSet<Preparate>();
        }
    
        public int RestaurantID { get; set; }
        public int OrasID { get; set; }
        public string Nume { get; set; }
        public string NumarTelefon { get; set; }
        public string Adresa { get; set; }
        public string Program { get; set; }
        public byte[] Poza { get; set; }
    
        public virtual Orase Orase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecenziiRestaurante> RecenziiRestaurante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozeRestaurante> PozeRestaurante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preparate> Preparate { get; set; }
    }
}
