//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervari
    {
        public int UserID { get; set; }
        public int CameraID { get; set; }
        public System.DateTime DataCheckin { get; set; }
        public System.DateTime DataCheckout { get; set; }
        public System.DateTime DataRezervarii { get; set; }
    
        public virtual Camere Camere { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
