//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TripAdvisorEntities : DbContext
    {
        public TripAdvisorEntities()
            : base("name=TripAdvisorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camere> Camere { get; set; }
        public virtual DbSet<CategoriiObiective> CategoriiObiective { get; set; }
        public virtual DbSet<Cazare> Cazare { get; set; }
        public virtual DbSet<Obiective> Obiective { get; set; }
        public virtual DbSet<Orase> Orase { get; set; }
        public virtual DbSet<Preparate> Preparate { get; set; }
        public virtual DbSet<RecenziiActivitati> RecenziiActivitati { get; set; }
        public virtual DbSet<RecenziiHoteluri> RecenziiHoteluri { get; set; }
        public virtual DbSet<RecenziiRestaurante> RecenziiRestaurante { get; set; }
        public virtual DbSet<Restaurante> Restaurante { get; set; }
        public virtual DbSet<Tari> Tari { get; set; }
        public virtual DbSet<Utilizatori> Utilizatori { get; set; }
        public virtual DbSet<PozeActivitati> PozeActivitati { get; set; }
        public virtual DbSet<PozeHotel> PozeHotel { get; set; }
        public virtual DbSet<PozeRestaurante> PozeRestaurante { get; set; }
        public virtual DbSet<Rezervari> Rezervari { get; set; }
    
        public virtual ObjectResult<getActivities_Result> getActivities(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getActivities_Result>("getActivities", orasParameter);
        }
    
        public virtual ObjectResult<getActivitiesbyType_Result> getActivitiesbyType(string oras, Nullable<int> categoryID)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getActivitiesbyType_Result>("getActivitiesbyType", orasParameter, categoryIDParameter);
        }
    
        public virtual ObjectResult<string> getActivitiesCategory(Nullable<int> activityID)
        {
            var activityIDParameter = activityID.HasValue ?
                new ObjectParameter("ActivityID", activityID) :
                new ObjectParameter("ActivityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getActivitiesCategory", activityIDParameter);
        }
    
        public virtual ObjectResult<getActivitiesDetails_Result> getActivitiesDetails(Nullable<int> activityID)
        {
            var activityIDParameter = activityID.HasValue ?
                new ObjectParameter("ActivityID", activityID) :
                new ObjectParameter("ActivityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getActivitiesDetails_Result>("getActivitiesDetails", activityIDParameter);
        }
    
        public virtual ObjectResult<getActivitiesPhotos_Result> getActivitiesPhotos(Nullable<int> obiectivID)
        {
            var obiectivIDParameter = obiectivID.HasValue ?
                new ObjectParameter("ObiectivID", obiectivID) :
                new ObjectParameter("ObiectivID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getActivitiesPhotos_Result>("getActivitiesPhotos", obiectivIDParameter);
        }
    
        public virtual ObjectResult<getActivityReviews_Result> getActivityReviews(Nullable<int> activityId)
        {
            var activityIdParameter = activityId.HasValue ?
                new ObjectParameter("activityId", activityId) :
                new ObjectParameter("activityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getActivityReviews_Result>("getActivityReviews", activityIdParameter);
        }
    
        public virtual ObjectResult<getHotelDetails_Result> getHotelDetails(Nullable<int> cazareId)
        {
            var cazareIdParameter = cazareId.HasValue ?
                new ObjectParameter("cazareId", cazareId) :
                new ObjectParameter("cazareId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHotelDetails_Result>("getHotelDetails", cazareIdParameter);
        }
    
        public virtual ObjectResult<getHotelPhotos_Result> getHotelPhotos(Nullable<int> cazareID)
        {
            var cazareIDParameter = cazareID.HasValue ?
                new ObjectParameter("cazareID", cazareID) :
                new ObjectParameter("cazareID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHotelPhotos_Result>("getHotelPhotos", cazareIDParameter);
        }
    
        public virtual ObjectResult<getHotelReviews_Result> getHotelReviews(Nullable<int> cazareId)
        {
            var cazareIdParameter = cazareId.HasValue ?
                new ObjectParameter("cazareId", cazareId) :
                new ObjectParameter("cazareId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHotelReviews_Result>("getHotelReviews", cazareIdParameter);
        }
    
        public virtual ObjectResult<getHotelRoomPhotos_Result> getHotelRoomPhotos(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHotelRoomPhotos_Result>("getHotelRoomPhotos", orasParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> getHotelRooms(Nullable<int> cazareId)
        {
            var cazareIdParameter = cazareId.HasValue ?
                new ObjectParameter("cazareId", cazareId) :
                new ObjectParameter("cazareId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getHotelRooms", cazareIdParameter);
        }
    
        public virtual ObjectResult<getHotels_Result> getHotels(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHotels_Result>("getHotels", orasParameter);
        }
    
        public virtual ObjectResult<getHotelsByRooms_Result> getHotelsByRooms(string oras, Nullable<int> numarPaturi)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            var numarPaturiParameter = numarPaturi.HasValue ?
                new ObjectParameter("NumarPaturi", numarPaturi) :
                new ObjectParameter("NumarPaturi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHotelsByRooms_Result>("getHotelsByRooms", orasParameter, numarPaturiParameter);
        }
    
        public virtual ObjectResult<getPreparate_Result> getPreparate(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPreparate_Result>("getPreparate", orasParameter);
        }
    
        public virtual ObjectResult<getRestaurantDetails_Result> getRestaurantDetails(Nullable<int> restId)
        {
            var restIdParameter = restId.HasValue ?
                new ObjectParameter("restId", restId) :
                new ObjectParameter("restId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRestaurantDetails_Result>("getRestaurantDetails", restIdParameter);
        }
    
        public virtual ObjectResult<string> getRestaurantMenu(Nullable<int> restId)
        {
            var restIdParameter = restId.HasValue ?
                new ObjectParameter("restId", restId) :
                new ObjectParameter("restId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getRestaurantMenu", restIdParameter);
        }
    
        public virtual ObjectResult<getRestaurantPhotos_Result> getRestaurantPhotos(Nullable<int> restaurantID)
        {
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("restaurantID", restaurantID) :
                new ObjectParameter("restaurantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRestaurantPhotos_Result>("getRestaurantPhotos", restaurantIDParameter);
        }
    
        public virtual ObjectResult<getRestaurantReviews_Result> getRestaurantReviews(Nullable<int> restId)
        {
            var restIdParameter = restId.HasValue ?
                new ObjectParameter("restId", restId) :
                new ObjectParameter("restId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRestaurantReviews_Result>("getRestaurantReviews", restIdParameter);
        }
    
        public virtual ObjectResult<getRestaurants_Result> getRestaurants(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRestaurants_Result>("getRestaurants", orasParameter);
        }
    
        public virtual ObjectResult<getRestaurantsByFood_Result> getRestaurantsByFood(string oras, Nullable<int> foodtype)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            var foodtypeParameter = foodtype.HasValue ?
                new ObjectParameter("Foodtype", foodtype) :
                new ObjectParameter("Foodtype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRestaurantsByFood_Result>("getRestaurantsByFood", orasParameter, foodtypeParameter);
        }
    
        public virtual ObjectResult<getTop3Activities_Result> getTop3Activities(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTop3Activities_Result>("getTop3Activities", orasParameter);
        }
    
        public virtual ObjectResult<getTop3Hotels_Result> getTop3Hotels(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTop3Hotels_Result>("getTop3Hotels", orasParameter);
        }
    
        public virtual ObjectResult<getTop3Restaurants_Result> getTop3Restaurants(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTop3Restaurants_Result>("getTop3Restaurants", orasParameter);
        }
    
        public virtual ObjectResult<getTypes_Result> getTypes(string oras)
        {
            var orasParameter = oras != null ?
                new ObjectParameter("Oras", oras) :
                new ObjectParameter("Oras", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTypes_Result>("getTypes", orasParameter);
        }
    }
}
